In [31]:
import pandas as pd  
from scipy import stats
import seaborn as sns 

In [32]:
data = {'col1':[1,1,1,1,1,1,1,1,1,10], 'col2':[10,1,1,1,10,1,1,1,1,1]}
df = pd.DataFrame(data)
df 

col1  col2
0     1    10
1     1     1
2     1     1
3     1     1
4     1    10
5     1     1
6     1     1
7     1     1
8     1     1
9    10     1

In [36]:
z_scores = stats.zscore(df)
z_scores 

array([[-0.33333333,  2.        ],
       [-0.33333333, -0.5       ],
       [-0.33333333, -0.5       ],
       [-0.33333333, -0.5       ],
       [-0.33333333,  2.        ],
       [-0.33333333, -0.5       ],
       [-0.33333333, -0.5       ],
       [-0.33333333, -0.5       ],
       [-0.33333333, -0.5       ],
       [ 3.        , -0.5       ]])

In [37]:
abs_z_scores = np.abs(z_scores)
abs_z_scores

array([[0.33333333, 2.        ],
       [0.33333333, 0.5       ],
       [0.33333333, 0.5       ],
       [0.33333333, 0.5       ],
       [0.33333333, 2.        ],
       [0.33333333, 0.5       ],
       [0.33333333, 0.5       ],
       [0.33333333, 0.5       ],
       [0.33333333, 0.5       ],
       [3.        , 0.5       ]])

In [38]:
filtered_entries = (abs_z_scores < 2).all(axis=1)
filtered_entries

array([False,  True,  True,  True, False,  True,  True,  True,  True,
       False])

In [39]:
new_df = df[filtered_entries]
new_df

col1  col2
1     1     1
2     1     1
3     1     1
5     1     1
6     1     1
7     1     1
8     1     1

In [41]:
import numpy as np 
def softmax(x):
    z = np.exp(x)
    print(z)
    z_ = z/z.sum()
    return z_

r = softmax([0.8,1.2,3.1])
r 


[ 2.22554093  3.32011692 22.19795128]


array([0.08021815, 0.11967141, 0.80011044])